apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-consul
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-consul
  nfs:
    path: /data/nfs/consul
    server: {{nfs_server}}